# Generated by Django 4.2.5 on 2023-09-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=40)),
                ('body', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
