# Generated by Django 4.2.5 on 2023-09-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nmodels',
            name='name',
        ),
        migrations.AddField(
            model_name='nmodels',
            name='body5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nmodels',
            name='status5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nmodels',
            name='title5',
            field=models.CharField(default='', max_length=40),
        ),
    ]
