# Generated by Django 4.2.5 on 2023-09-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nmodel2',
            new_name='Nmodel3',
        ),
        migrations.RenameField(
            model_name='nmodel3',
            old_name='body2',
            new_name='body3',
        ),
        migrations.RenameField(
            model_name='nmodel3',
            old_name='status2',
            new_name='status3',
        ),
        migrations.RenameField(
            model_name='nmodel3',
            old_name='title2',
            new_name='title3',
        ),
    ]
